function uiobj = SWFG
% This is the config file for generate UI for Sound Waveform Generator
% short for : swfg
% Updated @2016/7/20
sfnName = 'swfg';

index = 1;
% first element is the display string. headerfile, periname, funcpostname
% are stored in g_pv of S-function block.
uiobj(index).prompt = 'The SWFG is a function that generates and outputs a Pulse Code Modulation (PCM) sound source using simple software settings.';
uiobj(index).headerfile = 's6j3200_SWFG.h';
uiobj(index).periname = 'SWFG';                     % folder name of the upper layer.
uiobj(index).funcpostname = '_Init';
uiobj(index).arg = 'void';
uiobj(index).ret = 'void ';                         % with a blank after
% from second element control for registers begin
index = index + 1;
uiobj(index).prompt = 'Channel 0 Operation Enable';
uiobj(index).tabname = 'Global Settings';
uiobj(index).var = 'ench0';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';  
uiobj(index).Callback = {@en_disPanel, 'Channel 0'};
uiobj(index).helptip = 'Channel 0 operation enable/disable.';  
uiobj(index).regio = 'SWFG_WGCHEN_CH0EN';

index = index + 1;
uiobj(index).prompt = 'Channel 1 Operation Enable';
uiobj(index).tabname = 'Global Settings';
uiobj(index).var = 'ench1';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';       
uiobj(index).Callback = {@en_disPanel, 'Channel 1'};
uiobj(index).helptip = 'Channel 1 operation enable/disable.';  
uiobj(index).regio = 'SWFG_WGCHEN_CH1EN';

index = index + 1;
uiobj(index).prompt = 'Channel 2 Operation Enable';
uiobj(index).tabname = 'Global Settings';
uiobj(index).var = 'ench2';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';           
uiobj(index).Callback = {@en_disPanel, 'Channel 2'};
uiobj(index).helptip = 'Channel 2 operation enable/disable.';  
uiobj(index).regio = 'SWFG_WGCHEN_CH2EN';

index = index + 1;
uiobj(index).prompt = 'Channel 3 Operation Enable';
uiobj(index).tabname = 'Global Settings';
uiobj(index).var = 'ench3';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';          
uiobj(index).Callback = {@en_disPanel, 'Channel 3'};
uiobj(index).helptip = 'Channel 3 operation enable/disable.';  
uiobj(index).regio = 'SWFG_WGCHEN_CH3EN';

index = index + 1;
uiobj(index).prompt = 'Channel 4 Operation Enable';
uiobj(index).tabname = 'Global Settings';
uiobj(index).var = 'ench4';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';         
uiobj(index).Callback = {@en_disPanel, 'Channel 4'};
uiobj(index).helptip = 'Channel 4 operation enable/disable.';  
uiobj(index).regio = 'SWFG_WGCHEN_CH4EN';
% Interrupt
index = index + 1;
uiobj(index).prompt = 'Channel 0 sound source generation end interrupt Enable';
uiobj(index).tabname = 'Interrupt';
uiobj(index).var = 'ench0int';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';                    
uiobj(index).helptip = 'Channel 0 sound source generation end interrupt enable.';  
uiobj(index).regio = 'SWFG_WGINTREN_CH0END';

index = index + 1;
uiobj(index).prompt = 'Channel 1 sound source generation end interrupt Enable';
uiobj(index).tabname = 'Interrupt';
uiobj(index).var = 'ench1int';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';                    
uiobj(index).helptip = 'Channel 1 sound source generation end interrupt enable.';  
uiobj(index).regio = 'SWFG_WGINTREN_CH1END';

index = index + 1;
uiobj(index).prompt = 'Channel 2 sound source generation end interrupt Enable';
uiobj(index).tabname = 'Interrupt';
uiobj(index).var = 'ench2int';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';                    
uiobj(index).helptip = 'Channel 2 sound source generation end interrupt enable.';  
uiobj(index).regio = 'SWFG_WGINTREN_CH2END';

index = index + 1;
uiobj(index).prompt = 'Channel 3 sound source generation end interrupt Enable';
uiobj(index).tabname = 'Interrupt';
uiobj(index).var = 'ench3int';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';                    
uiobj(index).helptip = 'Channel 3 sound source generation end interrupt enable.';  
uiobj(index).regio = 'SWFG_WGINTREN_CH3END';

index = index + 1;
uiobj(index).prompt = 'Channel 4 sound source generation end interrupt Enable';
uiobj(index).tabname = 'Interrupt';
uiobj(index).var = 'ench4int';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';                    
uiobj(index).helptip = 'Channel 4 sound source generation end interrupt enable.';  
uiobj(index).regio = 'SWFG_WGINTREN_CH4END';

index = index + 1;
uiobj(index).prompt = 'AHB MASTER INTERFACE bus error interrupt Enable';
uiobj(index).tabname = 'Interrupt';
uiobj(index).var = 'enahbifint';              
uiobj(index).type = 'checkbox';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = 'on';                    
uiobj(index).helptip = 'AHB MASTER INTERFACE bus error interrupt enable.';  
uiobj(index).regio = 'SWFG_WGINTREN_AHBERR';

% Channel 0 configs begin
index = index + 1;
uiobj(index).prompt = 'Output destination address';
uiobj(index).tabname = 'Channel 0';
uiobj(index).var = 'ch0destaddr';              
uiobj(index).type = 'Edit';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench0');     
uiobj(index).Callback = {@numberCheck, 0, 2^13 - 1};
uiobj(index).helptip = 'Sets the Channel 0 output destination address as 13 bits.';  
uiobj(index).regio = 'SWFG_WGCHADD1_CH0ADD';

index = index + 1;
uiobj(index).prompt = 'Output data pattern';
uiobj(index).tabname = 'Channel 0';
uiobj(index).var = 'ch0datapattern';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Upper and lower 16 bits output the same data (XXXX_XXXX)';'Only lower 16 bits of data are output (0000_XXXX)';'Only upper 16 bits of data are output (XXXX_0000)'};
uiobj(index).val = 'Upper and lower 16 bits output the same data (XXXX_XXXX)';
uiobj(index).codegenstr = {'0';'1';'2'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench0');                    
uiobj(index).helptip = ' Channel 0 output data pattern.';  
uiobj(index).regio = 'SWFG_WGCHMONO_CH0MONO';

index = index + 1;
uiobj(index).prompt = 'Run time(ms)';
uiobj(index).tabname = 'Channel 0';
uiobj(index).var = 'ch0runtime';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';'1250';'1500';'2000';'2500';'3000';'3500';'4000';};
uiobj(index).val = '1';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(1:31)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench0');                     
uiobj(index).helptip = ' Channel 0 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH0CTRL1_FSLEN';

index = index + 1;
uiobj(index).prompt = 'Waveform';
uiobj(index).tabname = 'Channel 0';
uiobj(index).var = 'ch0wavfrm';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Sine wave';'Sawtooth wave';'Square wave'};
uiobj(index).val = 'Sine wave';
uiobj(index).codegenstr = {'0';'1';'2'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench0');                   
uiobj(index).helptip = ' Channel 0 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH0CTRL1_FSINF';

index = index + 1;
uiobj(index).prompt = 'Frequency(Hz)';
uiobj(index).tabname = 'Channel 0';
uiobj(index).var = 'ch0frq';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'110';'116.54';'123.47';'130.81';'138.59';'146.83';'155.56';'164.81';'174.61';'185.00';'196.00';'207.65';'220.00';'233.08';'246.94';'261.63';'277.18';'293.66';'311.13';'329.63';'349.23';'369.99';'392.00';'415.30';'440.00';'466.16';'493.88';'523.25';'554.37';'587.33';'622.25';'659.26';'698.46';'739.99';'783.99';'830.61';'880.00';'932.33';'987.77';'1046.50';'1108.73';'1174.66';'1244.51';'1318.51';'1396.91';'1479.98';'1567.98';'1661.22';'1760.00';'1864.66';'1975.53';'2093.00';'2217.46';'2349.32';'2489.02';'2637.02';'2793.83';'2959.96';'3135.96';'3322.44';'3520.00';'3729.31';'3951.07';'4186.01'};
uiobj(index).val = '110';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:63)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench0');                     
uiobj(index).helptip = ' Channel 0 output frequency.';  
uiobj(index).regio = 'SWFG_WGCH0CTRL1_FSFREQ';

index = index + 1;
uiobj(index).prompt = 'Start idle time(ms)';
uiobj(index).tabname = 'Channel 0';
uiobj(index).var = 'ch0stidletime';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';'1250';'1500';'2000';'2500';'3000';'3500';'4000';};
uiobj(index).val = '0';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:31)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench0');                   
uiobj(index).helptip = ' Channel 0 Start idle time.';  
uiobj(index).regio = 'SWFG_WGCH0CTRL2_ITVAL1';

index = index + 1;
uiobj(index).prompt = 'LF cutoff frequency';
uiobj(index).tabname = 'Channel 0';
uiobj(index).var = 'ch0lfcutofffreq';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Disable filter';'8KHz';'5KHz';'2KHz'};
uiobj(index).val = 'Disable filter';
uiobj(index).codegenstr = {'0';'1';'2';'3'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench0');                    
uiobj(index).helptip = ' Channel 0 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH0CTRL3_FILTER';

index = index + 1;
uiobj(index).prompt = 'Fade in time(ms)';
uiobj(index).tabname = 'Channel 0';
uiobj(index).var = 'ch0fadein';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Fade in control not used';'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';};  % repeat value Deny
uiobj(index).val = 'Fade in control not used';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:25)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench0');      
uiobj(index).Callback = {@requireCompareRelation,'SOUND WAVEFORM GENERATOR INIT', 'ch0runtime', '>'};
uiobj(index).helptip = 'Channel 0 fade in time is time required for volume change from -96 dB to 0 dB immediately following run time start.Fade in time is included in run time.';  
uiobj(index).regio = 'SWFG_WGCH0CTRL3_ATTACK';

index = index + 1;
uiobj(index).prompt = 'Fade out time(ms)';
uiobj(index).tabname = 'Channel 0';
uiobj(index).var = 'ch0fadeout';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Fade out control not used';'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';};  % repeat value Deny
uiobj(index).val = 'Fade out control not used';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:25)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench0');     
uiobj(index).Callback = {@requireCompareRelation,'SOUND WAVEFORM GENERATOR INIT', 'ch0runtime', '>'};
uiobj(index).helptip = 'Channel 0 fade out time is time required for volume change from 0 dB to -96 dB immediately following run time end. ';  
uiobj(index).regio = 'SWFG_WGCH0CTRL3_RELEASE';

% Channel 1 configs begin
index = index + 1;
uiobj(index).prompt = 'Output destination address';
uiobj(index).tabname = 'Channel 1';
uiobj(index).var = 'ch1destaddr';              
uiobj(index).type = 'Edit';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench1');     
uiobj(index).Callback = {@numberCheck, 0, 2^13 - 1};
uiobj(index).helptip = 'Sets the Channel 1 output destination address as 13 bits.';  
uiobj(index).regio = 'SWFG_WGCHADD1_CH1ADD';

index = index + 1;
uiobj(index).prompt = 'Output data pattern';
uiobj(index).tabname = 'Channel 1';
uiobj(index).var = 'ch1datapattern';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Upper and lower 16 bits output the same data (XXXX_XXXX)';'Only lower 16 bits of data are output (0000_XXXX)';'Only upper 16 bits of data are output (XXXX_0000)'};
uiobj(index).val = 'Upper and lower 16 bits output the same data (XXXX_XXXX)';
uiobj(index).codegenstr = {'0';'1';'2'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench1');                     
uiobj(index).helptip = ' Channel 1 output data pattern.';  
uiobj(index).regio = 'SWFG_WGCHMONO_CH1MONO';

index = index + 1;
uiobj(index).prompt = 'Run time(ms)';
uiobj(index).tabname = 'Channel 1';
uiobj(index).var = 'ch1runtime';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';'1250';'1500';'2000';'2500';'3000';'3500';'4000';};
uiobj(index).val = '1';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(1:31)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench1');                    
uiobj(index).helptip = ' Channel 1 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH1CTRL1_FSLEN';

index = index + 1;
uiobj(index).prompt = 'Waveform';
uiobj(index).tabname = 'Channel 1';
uiobj(index).var = 'ch1wavfrm';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Sine wave';'Sawtooth wave';'Square wave'};
uiobj(index).val = 'Sine wave';
uiobj(index).codegenstr = {'0';'1';'2'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench1');                     
uiobj(index).helptip = ' Channel 1 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH1CTRL1_FSINF';

index = index + 1;
uiobj(index).prompt = 'Frequency(Hz)';
uiobj(index).tabname = 'Channel 1';
uiobj(index).var = 'ch1frq';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'110';'116.54';'123.47';'130.81';'138.59';'146.83';'155.56';'164.81';'174.61';'185.00';'196.00';'207.65';'220.00';'233.08';'246.94';'261.63';'277.18';'293.66';'311.13';'329.63';'349.23';'369.99';'392.00';'415.30';'440.00';'466.16';'493.88';'523.25';'554.37';'587.33';'622.25';'659.26';'698.46';'739.99';'783.99';'830.61';'880.00';'932.33';'987.77';'1046.50';'1108.73';'1174.66';'1244.51';'1318.51';'1396.91';'1479.98';'1567.98';'1661.22';'1760.00';'1864.66';'1975.53';'2093.00';'2217.46';'2349.32';'2489.02';'2637.02';'2793.83';'2959.96';'3135.96';'3322.44';'3520.00';'3729.31';'3951.07';'4186.01'};
uiobj(index).val = '110';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:63)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench1');                     
uiobj(index).helptip = ' Channel 1 output frequency.';  
uiobj(index).regio = 'SWFG_WGCH1CTRL1_FSFREQ';

index = index + 1;
uiobj(index).prompt = 'Start idle time(ms)';
uiobj(index).tabname = 'Channel 1';
uiobj(index).var = 'ch1stidletime';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';'1250';'1500';'2000';'2500';'3000';'3500';'4000';};
uiobj(index).val = '0';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:31)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench1');                      
uiobj(index).helptip = ' Channel 1 Start idle time.';  
uiobj(index).regio = 'SWFG_WGCH1CTRL2_ITVAL1';

index = index + 1;
uiobj(index).prompt = 'LF cutoff frequency';
uiobj(index).tabname = 'Channel 1';
uiobj(index).var = 'ch1lfcutofffreq';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Disable filter';'8KHz';'5KHz';'2KHz'};
uiobj(index).val = 'Disable filter';
uiobj(index).codegenstr = {'0';'1';'2';'3'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench1');                   
uiobj(index).helptip = ' Channel 1 low pass filter frequency.';  
uiobj(index).regio = 'SWFG_WGCH1CTRL3_FILTER';

index = index + 1;
uiobj(index).prompt = 'Fade in time(ms)';
uiobj(index).tabname = 'Channel 1';
uiobj(index).var = 'ch1fadein';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Fade in control not used';'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';};
uiobj(index).val = 'Fade in control not used';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:25)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench1');    
uiobj(index).Callback = {@requireCompareRelation,'SOUND WAVEFORM GENERATOR INIT', 'ch1runtime', '>'};
uiobj(index).helptip = 'Channel 1 fade in time is time required for volume change from -96 dB to 0 dB immediately following run time start.Fade in time is included in run time.';  
uiobj(index).regio = 'SWFG_WGCH1CTRL3_ATTACK';

index = index + 1;
uiobj(index).prompt = 'Fade out time(ms)';
uiobj(index).tabname = 'Channel 1';
uiobj(index).var = 'ch1fadeout';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Fade out control not used';'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';};
uiobj(index).val = 'Fade out control not used';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:25)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench1');    
uiobj(index).Callback = {@requireCompareRelation,'SOUND WAVEFORM GENERATOR INIT', 'ch1runtime', '>'};
uiobj(index).helptip = 'Channel 1 fade out time is time required for volume change from 0 dB to -96 dB immediately following run time end. ';  
uiobj(index).regio = 'SWFG_WGCH1CTRL3_RELEASE';

% Channel 2 configs begin
index = index + 1;
uiobj(index).prompt = 'Output destination address';
uiobj(index).tabname = 'Channel 2';
uiobj(index).var = 'ch2destaddr';              
uiobj(index).type = 'Edit';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench2');    
uiobj(index).Callback = {@numberCheck, 0, 2^13 - 1};
uiobj(index).helptip = 'Sets the Channel 2 output destination address as 13 bits.';  
uiobj(index).regio = 'SWFG_WGCHADD1_CH2ADD';

index = index + 1;
uiobj(index).prompt = 'Output data pattern';
uiobj(index).tabname = 'Channel 2';
uiobj(index).var = 'ch2datapattern';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Upper and lower 16 bits output the same data (XXXX_XXXX)';'Only lower 16 bits of data are output (0000_XXXX)';'Only upper 16 bits of data are output (XXXX_0000)'};
uiobj(index).val = 'Upper and lower 16 bits output the same data (XXXX_XXXX)';
uiobj(index).codegenstr = {'0';'1';'2'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench2');                     
uiobj(index).helptip = ' Channel 2 output data pattern.';  
uiobj(index).regio = 'SWFG_WGCHMONO_CH2MONO';

index = index + 1;
uiobj(index).prompt = 'Run time(ms)';
uiobj(index).tabname = 'Channel 2';
uiobj(index).var = 'ch2runtime';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';'1250';'1500';'2000';'2500';'3000';'3500';'4000';};
uiobj(index).val = '1';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(1:31)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench2');                     
uiobj(index).helptip = ' Channel 2 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH2CTRL1_FSLEN';

index = index + 1;
uiobj(index).prompt = 'Waveform';
uiobj(index).tabname = 'Channel 2';
uiobj(index).var = 'ch2wavfrm';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Sine wave';'Sawtooth wave';'Square wave'};
uiobj(index).val = 'Sine wave';
uiobj(index).codegenstr = {'0';'1';'2'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench2');                      
uiobj(index).helptip = ' Channel 2 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH2CTRL1_FSINF';

index = index + 1;
uiobj(index).prompt = 'Frequency(Hz)';
uiobj(index).tabname = 'Channel 2';
uiobj(index).var = 'ch2frq';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'110';'116.54';'123.47';'130.81';'138.59';'146.83';'155.56';'164.81';'174.61';'185.00';'196.00';'207.65';'220.00';'233.08';'246.94';'261.63';'277.18';'293.66';'311.13';'329.63';'349.23';'369.99';'392.00';'415.30';'440.00';'466.16';'493.88';'523.25';'554.37';'587.33';'622.25';'659.26';'698.46';'739.99';'783.99';'830.61';'880.00';'932.33';'987.77';'1046.50';'1108.73';'1174.66';'1244.51';'1318.51';'1396.91';'1479.98';'1567.98';'1661.22';'1760.00';'1864.66';'1975.53';'2093.00';'2217.46';'2349.32';'2489.02';'2637.02';'2793.83';'2959.96';'3135.96';'3322.44';'3520.00';'3729.31';'3951.07';'4186.01'};
uiobj(index).val = '110';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:63)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench2');                      
uiobj(index).helptip = ' Channel 2 output frequency.';  
uiobj(index).regio = 'SWFG_WGCH2CTRL1_FSFREQ';

index = index + 1;
uiobj(index).prompt = 'Start idle time(ms)';
uiobj(index).tabname = 'Channel 2';
uiobj(index).var = 'ch2stidletime';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';'1250';'1500';'2000';'2500';'3000';'3500';'4000';};
uiobj(index).val = '0';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:31)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench2');                      
uiobj(index).helptip = ' Channel 2 Start idle time.';  
uiobj(index).regio = 'SWFG_WGCH2CTRL2_ITVAL1';

index = index + 1;
uiobj(index).prompt = 'LF cutoff frequency';
uiobj(index).tabname = 'Channel 2';
uiobj(index).var = 'ch2lfcutofffreq';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Disable filter';'8KHz';'5KHz';'2KHz'};
uiobj(index).val = 'Disable filter';
uiobj(index).codegenstr = {'0';'1';'2';'3'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench2');                    
uiobj(index).helptip = ' Channel 2 low pass filter frequency.';  
uiobj(index).regio = 'SWFG_WGCH2CTRL3_FILTER';

index = index + 1;
uiobj(index).prompt = 'Fade in time(ms)';
uiobj(index).tabname = 'Channel 2';
uiobj(index).var = 'ch2fadein';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Fade in control not used';'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';};
uiobj(index).val = 'Fade in control not used';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:25)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench2');   
uiobj(index).Callback = {@requireCompareRelation,'SOUND WAVEFORM GENERATOR INIT', 'ch2runtime', '>'};
uiobj(index).helptip = 'Channel 2 fade in time is time required for volume change from -96 dB to 0 dB immediately following run time start.Fade in time is included in run time.';  
uiobj(index).regio = 'SWFG_WGCH2CTRL3_ATTACK';

index = index + 1;
uiobj(index).prompt = 'Fade out time(ms)';
uiobj(index).tabname = 'Channel 2';
uiobj(index).var = 'ch2fadeout';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Fade out control not used';'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';};
uiobj(index).val = 'Fade out control not used';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:25)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench2');  
uiobj(index).Callback = {@requireCompareRelation,'SOUND WAVEFORM GENERATOR INIT', 'ch2runtime', '>'};
uiobj(index).helptip = 'Channel 2 fade out time is time required for volume change from 0 dB to -96 dB immediately following run time end. ';  
uiobj(index).regio = 'SWFG_WGCH2CTRL3_RELEASE';

% Channel 3 configs begin
index = index + 1;
uiobj(index).prompt = 'Output destination address';
uiobj(index).tabname = 'Channel 3';
uiobj(index).var = 'ch3destaddr';              
uiobj(index).type = 'Edit';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench3');       
uiobj(index).Callback = {@numberCheck, 0, 2^13 - 1};
uiobj(index).helptip = 'Sets the Channel 3 output destination address as 13 bits.';  
uiobj(index).regio = 'SWFG_WGCHADD1_CH3ADD';

index = index + 1;
uiobj(index).prompt = 'Output data pattern';
uiobj(index).tabname = 'Channel 3';
uiobj(index).var = 'ch3datapattern';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Upper and lower 16 bits output the same data (XXXX_XXXX)';'Only lower 16 bits of data are output (0000_XXXX)';'Only upper 16 bits of data are output (XXXX_0000)'};
uiobj(index).val = 'Upper and lower 16 bits output the same data (XXXX_XXXX)';
uiobj(index).codegenstr = {'0';'1';'2'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench3');                    
uiobj(index).helptip = ' Channel 3 output data pattern.';  
uiobj(index).regio = 'SWFG_WGCHMONO_CH3MONO';

index = index + 1;
uiobj(index).prompt = 'Run time(ms)';
uiobj(index).tabname = 'Channel 3';
uiobj(index).var = 'ch3runtime';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';'1250';'1500';'2000';'2500';'3000';'3500';'4000';};
uiobj(index).val = '1';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(1:31)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench3');                    
uiobj(index).helptip = ' Channel 3 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH3CTRL1_FSLEN';

index = index + 1;
uiobj(index).prompt = 'Waveform';
uiobj(index).tabname = 'Channel 3';
uiobj(index).var = 'ch3wavfrm';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Sine wave';'Sawtooth wave';'Square wave'};
uiobj(index).val = 'Sine wave';
uiobj(index).codegenstr = {'0';'1';'2'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench3');                   
uiobj(index).helptip = ' Channel 3 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH3CTRL1_FSINF';

index = index + 1;
uiobj(index).prompt = 'Frequency(Hz)';
uiobj(index).tabname = 'Channel 3';
uiobj(index).var = 'ch3frq';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'110';'116.54';'123.47';'130.81';'138.59';'146.83';'155.56';'164.81';'174.61';'185.00';'196.00';'207.65';'220.00';'233.08';'246.94';'261.63';'277.18';'293.66';'311.13';'329.63';'349.23';'369.99';'392.00';'415.30';'440.00';'466.16';'493.88';'523.25';'554.37';'587.33';'622.25';'659.26';'698.46';'739.99';'783.99';'830.61';'880.00';'932.33';'987.77';'1046.50';'1108.73';'1174.66';'1244.51';'1318.51';'1396.91';'1479.98';'1567.98';'1661.22';'1760.00';'1864.66';'1975.53';'2093.00';'2217.46';'2349.32';'2489.02';'2637.02';'2793.83';'2959.96';'3135.96';'3322.44';'3520.00';'3729.31';'3951.07';'4186.01'};
uiobj(index).val = '110';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:63)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench3');                    
uiobj(index).helptip = ' Channel 3 output frequency.';  
uiobj(index).regio = 'SWFG_WGCH3CTRL1_FSFREQ';

index = index + 1;
uiobj(index).prompt = 'Start idle time(ms)';
uiobj(index).tabname = 'Channel 3';
uiobj(index).var = 'ch3stidletime';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';'1250';'1500';'2000';'2500';'3000';'3500';'4000';};
uiobj(index).val = '0';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:31)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench3');                    
uiobj(index).helptip = ' Channel 3 Start idle time.';  
uiobj(index).regio = 'SWFG_WGCH3CTRL2_ITVAL1';

index = index + 1;
uiobj(index).prompt = 'LF cutoff frequency';
uiobj(index).tabname = 'Channel 3';
uiobj(index).var = 'ch3lfcutofffreq';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Disable filter';'8KHz';'5KHz';'2KHz'};
uiobj(index).val = 'Disable filter';
uiobj(index).codegenstr = {'0';'1';'2';'3'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench3');                    
uiobj(index).helptip = ' Channel 3 low pass filter frequency.';  
uiobj(index).regio = 'SWFG_WGCH3CTRL3_FILTER';

index = index + 1;
uiobj(index).prompt = 'Fade in time(ms)';
uiobj(index).tabname = 'Channel 3';
uiobj(index).var = 'ch3fadein';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Fade in control not used';'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';};
uiobj(index).val = 'Fade in control not used';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:25)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench3');  
uiobj(index).Callback = {@requireCompareRelation,'SOUND WAVEFORM GENERATOR INIT', 'ch3runtime', '>'};
uiobj(index).helptip = 'Channel 3 fade in time is time required for volume change from -96 dB to 0 dB immediately following run time start.Fade in time is included in run time.';  
uiobj(index).regio = 'SWFG_WGCH3CTRL3_ATTACK';

index = index + 1;
uiobj(index).prompt = 'Fade out time(ms)';
uiobj(index).tabname = 'Channel 3';
uiobj(index).var = 'ch3fadeout';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Fade out control not used';'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';};
uiobj(index).val = 'Fade out control not used';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:25)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench3');    
uiobj(index).Callback = {@requireCompareRelation,'SOUND WAVEFORM GENERATOR INIT', 'ch3runtime', '>'};
uiobj(index).helptip = 'Channel 3 fade out time is time required for volume change from 0 dB to -96 dB immediately following run time end. ';  
uiobj(index).regio = 'SWFG_WGCH3CTRL3_RELEASE';

% Channel 4 configs begin
index = index + 1;
uiobj(index).prompt = 'Output destination address';
uiobj(index).tabname = 'Channel 4';
uiobj(index).var = 'ch4destaddr';              
uiobj(index).type = 'Edit';
uiobj(index).val = '0';
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench4');    
uiobj(index).Callback = {@numberCheck, 0, 2^13 - 1};
uiobj(index).helptip = 'Sets the Channel 4 output destination address as 13 bits.';  
uiobj(index).regio = 'SWFG_WGCHADD1_CH4ADD';

index = index + 1;
uiobj(index).prompt = 'Output data pattern';
uiobj(index).tabname = 'Channel 4';
uiobj(index).var = 'ch4datapattern';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Upper and lower 16 bits output the same data (XXXX_XXXX)';'Only lower 16 bits of data are output (0000_XXXX)';'Only upper 16 bits of data are output (XXXX_0000)'};
uiobj(index).val = 'Upper and lower 16 bits output the same data (XXXX_XXXX)';
uiobj(index).codegenstr = {'0';'1';'2'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench4');                     
uiobj(index).helptip = ' Channel 4 output data pattern.';  
uiobj(index).regio = 'SWFG_WGCHMONO_CH4MONO';

index = index + 1;
uiobj(index).prompt = 'Run time(ms)';
uiobj(index).tabname = 'Channel 4';
uiobj(index).var = 'ch4runtime';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';'1250';'1500';'2000';'2500';'3000';'3500';'4000';};
uiobj(index).val = '1';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(1:31)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench4');                     
uiobj(index).helptip = ' Channel 4 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH4CTRL1_FSLEN';

index = index + 1;
uiobj(index).prompt = 'Waveform';
uiobj(index).tabname = 'Channel 4';
uiobj(index).var = 'ch4wavfrm';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Sine wave';'Sawtooth wave';'Square wave'};
uiobj(index).val = 'Sine wave';
uiobj(index).codegenstr = {'0';'1';'2'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench4');                    
uiobj(index).helptip = ' Channel 4 run time(the time to generate a sound source of the specified frequency).';  
uiobj(index).regio = 'SWFG_WGCH4CTRL1_FSINF';

index = index + 1;
uiobj(index).prompt = 'Frequency(Hz)';
uiobj(index).tabname = 'Channel 4';
uiobj(index).var = 'ch4frq';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'110';'116.54';'123.47';'130.81';'138.59';'146.83';'155.56';'164.81';'174.61';'185.00';'196.00';'207.65';'220.00';'233.08';'246.94';'261.63';'277.18';'293.66';'311.13';'329.63';'349.23';'369.99';'392.00';'415.30';'440.00';'466.16';'493.88';'523.25';'554.37';'587.33';'622.25';'659.26';'698.46';'739.99';'783.99';'830.61';'880.00';'932.33';'987.77';'1046.50';'1108.73';'1174.66';'1244.51';'1318.51';'1396.91';'1479.98';'1567.98';'1661.22';'1760.00';'1864.66';'1975.53';'2093.00';'2217.46';'2349.32';'2489.02';'2637.02';'2793.83';'2959.96';'3135.96';'3322.44';'3520.00';'3729.31';'3951.07';'4186.01'};
uiobj(index).val = '110';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:63)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench4');                     
uiobj(index).helptip = ' Channel 4 output frequency.';  
uiobj(index).regio = 'SWFG_WGCH4CTRL1_FSFREQ';

index = index + 1;
uiobj(index).prompt = 'Start idle time(ms)';
uiobj(index).tabname = 'Channel 4';
uiobj(index).var = 'ch4stidletime';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';'1250';'1500';'2000';'2500';'3000';'3500';'4000';};
uiobj(index).val = '0';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:31)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench4');                     
uiobj(index).helptip = ' Channel 4 Start idle time.';  
uiobj(index).regio = 'SWFG_WGCH4CTRL2_ITVAL1';

index = index + 1;
uiobj(index).prompt = 'LF cutoff frequency';
uiobj(index).tabname = 'Channel 4';
uiobj(index).var = 'ch4lfcutofffreq';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Disable filter';'8KHz';'5KHz';'2KHz'};
uiobj(index).val = 'Disable filter';
uiobj(index).codegenstr = {'0';'1';'2';'3'};
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench4');                     
uiobj(index).helptip = ' Channel 4 low pass filter frequency.';  
uiobj(index).regio = 'SWFG_WGCH4CTRL3_FILTER';

index = index + 1;
uiobj(index).prompt = 'Fade in time(ms)';
uiobj(index).tabname = 'Channel 4';
uiobj(index).var = 'ch4fadein';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Fade in control not used';'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';};
uiobj(index).val = 'Fade in control not used';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:25)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench4');   
uiobj(index).Callback = {@requireCompareRelation,'SOUND WAVEFORM GENERATOR INIT', 'ch4runtime', '>'};
uiobj(index).helptip = 'Channel 4 fade in time is time required for volume change from -96 dB to 0 dB immediately following run time start.Fade in time is included in run time.';  
uiobj(index).regio = 'SWFG_WGCH4CTRL3_ATTACK';

index = index + 1;
uiobj(index).prompt = 'Fade out time(ms)';
uiobj(index).tabname = 'Channel 4';
uiobj(index).var = 'ch4fadeout';              
uiobj(index).type = 'popupmenu';
uiobj(index).members = {'Fade out control not used';'0';'1';'2';'3';'4';'5';'7.5';'10';'15';'20';'25';'30';'40';'50';'75';'100';'125';'150';'200';'250';'300';'400';'500';'750';'1000';};
uiobj(index).val = 'Fade out control not used';
uiobj(index).codegenstr = cellfun(@num2str, num2cell(0:25)', 'UniformOutput', false);
uiobj(index).visible = 'on';
uiobj(index).enable = initCheckboxEnable(find_system_unique('SOUND WAVEFORM GENERATOR INIT'), 'ench4');     
uiobj(index).Callback = {@requireCompareRelation,'SOUND WAVEFORM GENERATOR INIT', 'ch4runtime', '>'};
uiobj(index).helptip = 'Channel 4 fade out time is time required for volume change from 0 dB to -96 dB immediately following run time end. ';  
uiobj(index).regio = 'SWFG_WGCH4CTRL3_RELEASE';

index = index + 1;
uiobj(index).prompt = 'Cancel';
uiobj(index).helptip = 'Cancel this configuration and close UI.';
uiobj(index).Callback = 'close(gcf)';

index = index + 1;
uiobj(index).prompt = 'OK';
uiobj(index).Callback = {@okbuttoncb, uiobj, sfnName};
uiobj(index).type = 'pushbutton';
uiobj(index).helptip = 'OK this configuration and close UI.';

